
namespace CS_Java_VM.Src.Java.Constants;

public enum E_ConstantPoolTag {
  CONSTANT_UTF8 = 1,
  CONSTANT_INTEGER = 3,
  CONSTANT_FLOAT = 4,
  CONSTANT_LONG = 5,
  CONSTANT_DOUBLE = 6,
  CONSTANT_CLASS = 7,
  CONSTNAT_FIELDREF = 9,
  CONSTANT_STRING = 8,
  CONSTANT_METHODREF = 10,
  CONSTANT_INTERFACEMETHODREF = 11,
  CONSTANT_NAMEANDTYPE = 12,
  CONSTANT_METHODHANDLE = 15,
  CONSTANT_METHODTYPE = 16,
  CONSTANT_DYNAMIC = 17,
  CONSTANT_INVOKEDYNAMIC = 18,
  CONSTANT_MODULE = 19,
  CONSTANT_PACKAGE = 20,
}
